require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/account_records', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # AccountRecord. As you add validations to AccountRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      AccountRecord.create! valid_attributes
      get account_records_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      account_record = AccountRecord.create! valid_attributes
      get account_record_url(account_record)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_account_record_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      account_record = AccountRecord.create! valid_attributes
      get edit_account_record_url(account_record)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new AccountRecord' do
        expect do
          post account_records_url, params: { account_record: valid_attributes }
        end.to change(AccountRecord, :count).by(1)
      end

      it 'redirects to the created account_record' do
        post account_records_url, params: { account_record: valid_attributes }
        expect(response).to redirect_to(account_record_url(AccountRecord.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new AccountRecord' do
        expect do
          post account_records_url, params: { account_record: invalid_attributes }
        end.to change(AccountRecord, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post account_records_url, params: { account_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested account_record' do
        account_record = AccountRecord.create! valid_attributes
        patch account_record_url(account_record), params: { account_record: new_attributes }
        account_record.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the account_record' do
        account_record = AccountRecord.create! valid_attributes
        patch account_record_url(account_record), params: { account_record: new_attributes }
        account_record.reload
        expect(response).to redirect_to(account_record_url(account_record))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        account_record = AccountRecord.create! valid_attributes
        patch account_record_url(account_record), params: { account_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested account_record' do
      account_record = AccountRecord.create! valid_attributes
      expect do
        delete account_record_url(account_record)
      end.to change(AccountRecord, :count).by(-1)
    end

    it 'redirects to the account_records list' do
      account_record = AccountRecord.create! valid_attributes
      delete account_record_url(account_record)
      expect(response).to redirect_to(account_records_url)
    end
  end
end
