require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/operations', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Operation. As you add validations to Operation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Operation.create! valid_attributes
      get operations_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      operation = Operation.create! valid_attributes
      get operation_url(operation)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_operation_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      operation = Operation.create! valid_attributes
      get edit_operation_url(operation)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Operation' do
        expect do
          post operations_url, params: { operation: valid_attributes }
        end.to change(Operation, :count).by(1)
      end

      it 'redirects to the created operation' do
        post operations_url, params: { operation: valid_attributes }
        expect(response).to redirect_to(operation_url(Operation.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Operation' do
        expect do
          post operations_url, params: { operation: invalid_attributes }
        end.to change(Operation, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post operations_url, params: { operation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested operation' do
        operation = Operation.create! valid_attributes
        patch operation_url(operation), params: { operation: new_attributes }
        operation.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the operation' do
        operation = Operation.create! valid_attributes
        patch operation_url(operation), params: { operation: new_attributes }
        operation.reload
        expect(response).to redirect_to(operation_url(operation))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        operation = Operation.create! valid_attributes
        patch operation_url(operation), params: { operation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested operation' do
      operation = Operation.create! valid_attributes
      expect do
        delete operation_url(operation)
      end.to change(Operation, :count).by(-1)
    end

    it 'redirects to the operations list' do
      operation = Operation.create! valid_attributes
      delete operation_url(operation)
      expect(response).to redirect_to(operations_url)
    end
  end
end
